const c = Object.freeze({
    COLECCION_PRINCIPAL :'EMPRESA',
      FORMATO_FECHA  :'YYYY/MM/DD',
    MESES:{'ENERO':'ENERO','FEBRERO':'FEBRERO','MARZO':'MARZO','ABRIL':'ABRIL','MAYO':'MAYO','JUNIO':'JUNIO','JULIO':'JULIO','AGOSTO':'AGOSTO','SEPTIEMBRE':'SEPTIEMBRE','OCTUBRE':'OCTUBRE','NOVIEMBRE':'NOVIEMBRE','DICIEMBRE':'DICIEMBRE'},
    MESES_DIFERIDO: {'1':'1','2':'2','3':'3','4':'4','5':'5','6':'6','7':'7','8':'8','9':'9','10':'10','11':'11','12':'12'},
    TIPO_PERSONA: {'NATURAL':'NATURAL','JURIDICA':'JURIDICA'},
    ACTION_TIPO: {'INICIAR_SESION':'INICIAR_SESION','SALIR_SESION':'SALIR_SESION'},
    ESTADO_FUNCIONAL:{'ACTIVO':'ACTIVO','DESACTIVADO':'DESACTIVADO'},
    ESTADO_MEDIDOR:{'ACTIVO':'ACTIVO','DESACTIVADO':'DESACTIVADO','SUSPENDIDO':'SUSPENDIDO'},
    ESTADO_FACTURACION:{'NO_GENERADA':'NO GENERADA','GENERADA':'GENERADA','PAGADO':'PAGADO','ANULADA':'ANULADA'},
    ESTADO_PAGO:{'PAGADO':'PAGADO','PENDIENTE':'PENDIENTE', 'CONVENIO_PAGO':'CONVENIO DE PAGO'},
    ESTADO_BORRADO:{'BORRADO':'BORRADO','RESTAURADO':'RESTAURADO','NO_BORRADO':'NO_BORRADO'},
    ESTADO:{'ACTIVO':'ACTIVO','DESACTIVADO':'DESACTIVADO'},
    TIPO_IMPUESTO:{'2':'IVA','3':'ICE','5':'IRBPNR'},
    TARIFA_DEL_IVA:{'CERO':'0', 'DOCE':'2', '3':'CATORCE', 'No Objeto de Impuesto':'6','Exento de IVA':'7'},
    IMPUESTO_A_RETENER:{'1':'RENTA', '2':'IVA', '6':'ISD'},
    RETENCION_DE_IVA: {'9':'10%','10':'20%','1':'30%','11':'50%','2':'70%','3':'100%','7':'0','8':'0%'},
    IMPUESTO_IVA:'0.12',
    UNIDAD_DE_TIEMPO :{'DIAS':'DIAS', 'SEMANAS':'SEMANAS','MESES':'MESES','AÑOS':'AÑOS'},
    UNIDAD_DE_MEDIDA:{'UNIDAD':'UNIDAD','M':'METRO','KM':'KILOMETRO','G':'GRAMO','KG':'KILOGRAMO','L':'LITRO','':'','':'','':'','':''},
    CARPETA_LOGOS:'LOGOS',
    CARPETA_FIRMAS:'FIRMAS',
    CARPETA_FACTURAS:'FACTURAS'
  });

  export default c;